apps/cart/urls.py
from django.urls import path
from .views import cart_view, add_to_cart, increase_item_quantity, decrease_item_quantity, hx_cart_button, \
    update_cart_summary, remove_cart_item, get_cart_items, hx_empty_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart'),
    path('add/<slug:product_slug>/', add_to_cart, name='add_to_cart'),
    path('increase/<slug:product_slug>/', increase_item_quantity, name='increase_item_quantity'),
    path('decrease/<slug:product_slug>/', decrease_item_quantity, name='decrease_item_quantity'),
    path('remove/<slug:product_slug>/', remove_cart_item, name='remove_cart_item'),
    path('update', update_cart_summary, name="update_cart_summary"),
    path('get_cart_items', get_cart_items, name='get_cart_items'),
    path('hx_cart_button', hx_cart_button, name='hx_cart_button'),
    path('empty_cart', hx_empty_cart, name='hx_empty_cart'),
]

apps/coupons/urls.py
from django.urls import path
from .views import apply_coupon, remove_coupon

app_name = 'coupons'

urlpatterns = [
    path('apply/', apply_coupon, name='apply_coupon'),
    path('remove/', remove_coupon, name='remove_coupon'),
]

apps/orders/urls.py
from django.urls import path
from .views import create_order, get_order_items, update_order_summary, order_pdf

app_name = 'orders'

urlpatterns = [
    path('create/', create_order, name='create_order'),
    path('get_order_items', get_order_items, name='get_order_items'),
    path('update_order_summary', update_order_summary, name='update_order_summary'),
    path('<int:order_id>/pdf/', order_pdf, name='order_pdf')
]

apps/payment/urls.py
from django.urls import path
from .views import process_payment, payment_completed, payment_cancelled
from .webhooks import stripe_webhook

app_name = 'payment'

urlpatterns = [
    path('process/', process_payment, name='process'),
    path('completed/', payment_completed, name='completed'),
    path('canceled/', payment_cancelled, name='canceled'),
    path('webhook/', stripe_webhook, name='stripe_webhook'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/', include('apps.accounts.urls')),
    path('', include('apps.products.urls')),
    path('cart/', include('apps.cart.urls')),
    path('order/', include('apps.orders.urls')),
    path('coupon/', include('apps.coupons.urls')),
    path('payment/', include('apps.payment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/coupons/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
from django.utils import timezone


class Coupon(models.Model):
    DISCOUNT_TYPES = (
        ('Percentage', 'Percentage'),
        ('Fixed', 'Fixed'),
    )

    code = models.CharField(max_length=50, unique=True)
    discount_type = models.CharField(max_length=10, choices=DISCOUNT_TYPES)
    value = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text='The discount value, either a percentage or a fixed amount.'
    )
    valid_from = models.DateField()
    valid_to = models.DateField()
    max_usage = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text='Maximum number of times this coupon can be used.'
    )
    used_count = models.PositiveIntegerField(
        default=0,
        editable=False,
        help_text='Number of times this coupon has been used.'
    )
    active = models.BooleanField(
        help_text='Indicates whether the coupon is currently active or not.'
    )

    class Meta:
        ordering = ['valid_from']

    def __str__(self):
        return self.code

apps/orders/models.py
import uuid
from django.db import models
from django.utils import timezone
from apps.products.models import Product
from django.conf import settings


# Create your models here.


def generate_order_id():
    timestamp = timezone.now().strftime('%Y%m%d%H%M%S')
    unique_id = str(uuid.uuid4())[:6]
    order_id = f'ORD-{timestamp}-{unique_id}'
    return order_id


class Order(models.Model):
    ORDER_STATUS = [
        ('pending', 'Pending'),
        ('successful', 'Successful'),
        ('failed', 'Failed'),
        ('delivering', 'Delivering'),
    ]

    order_id = models.CharField(max_length=50, unique=True)
    first_name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField()
    address = models.CharField(max_length=256)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='pending')
    stripe_id = models.CharField(max_length=250, blank=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Order: {self.order_id}'

    def save(self, *args, **kwargs):
        if not self.order_id:
            self.order_id = generate_order_id()
        super().save(*args, **kwargs)

    @property
    def total_price(self):
        return sum(item.total_price for item in self.items.all())

    def get_stripe_url(self):
        if not self.stripe_id:
            # No payment associated
            return ''
        if '_test_' in settings.STRIPE_SECRET_KEY:
            # Stripe path for test payments
            path = '/test/'
        else:
            path = '/'
        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def total_price(self):
        return self.price * self.quantity

apps/coupons/forms.py
from django import forms
from .models import Coupon


class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ['code', 'discount_type', 'value', 'valid_to', 'valid_from', 'max_usage',
                  'active']


class ApplyCouponForm(forms.Form):
    code = forms.CharField()

apps/orders/forms.py
from django import forms
from .models import Order


class OrderCreationForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name', 'last_name', 'email', 'address', 'country', 'zip_code'
        ]

apps/coupons/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from .forms import ApplyCouponForm
from .models import Coupon
from apps.cart.views import get_cart


# Create your views here.

def apply_coupon(request):
    """
    View function to handle the coupon application process.

    This view retrieves the current cart, validates the coupon form,
    and applies the coupon to the cart if it is valid.

    """
    cart = get_cart(request)
    now = timezone.now()
    coupon_code = request.POST.get('code')

    if request.method == 'POST':
        try:
            coupon = Coupon.objects.get(code__iexact=coupon_code,
                                        valid_from__lte=now,
                                        valid_to__gte=now,
                                        active=True)
        except Coupon.DoesNotExist:
            messages.error(request, 'Invalid coupon code.')
        else:
            if cart.coupon and cart.coupon.code == coupon.code:
                messages.error(request, 'The coupon is already applied to your cart.')
            elif coupon.active:
                cart.coupon = coupon
                cart.save()
                messages.success(request, 'Coupon applied successfully.')
            else:
                messages.error(request, 'The coupon is no longer valid.')

    response = HttpResponse(status=204)
    response['HX-Trigger'] = 'update-cart'
    return response


def remove_coupon(request):
    """
    View function to handle the coupon removal process.

    This view retrieves the current cart and removes the applied
    coupon if one exists.

    """
    cart = get_cart(request)  # Get the current cart

    if cart.coupon:
        coupon = cart.coupon  # Get the applied coupon
        cart.coupon = None  # Remove the coupon from the cart
        cart.save()  # Save the cart without the coupon
        messages.success(request, f'Coupon "{coupon.code}" has been removed.')  # Display a success message
    else:
        messages.error(request, 'There is no coupon applied to your cart.')  # Display an error message

    response = HttpResponse(status=204)
    response['HX-Trigger'] = 'update-cart'
    return response

apps/orders/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from .forms import OrderCreationForm
from .models import OrderItem, Order
from .tasks import order_created
from apps.cart.views import get_cart
import weasyprint


# Create your views here.


def get_order_items(request):
    cart = get_cart(request)
    cart_items = cart.items.all()
    context = {
        'cart_items': cart_items
    }
    return render(request, 'orders/partials/order-item-list.html', context)


def update_order_summary(request):
    # Get the cart
    cart = get_cart(request)

    # Get the subtotal, price and total price based on the updated cart item
    subtotal = cart.subtotal
    tax = cart.tax_amount
    total_price = cart.total_price
    discount = cart.display_discount

    context = {
        'subtotal': subtotal,
        'tax': tax,
        'total_price': total_price,
        'discount': discount
    }
    return render(request, 'orders/partials/order-summary.html', context)


def create_order(request):
    cart = get_cart(request)
    cart_items = cart.items.all() if request.method == 'GET' else []  # Initialize cart_items conditionally

    if request.method == 'POST':
        form = OrderCreationForm(request.POST)
        if form.is_valid():
            order = form.save()

            # Create order items based on cart items
            OrderItem.objects.create([
                OrderItem(order=order, product=item.product, price=item.price, quantity=item.quantity)
                for item in cart_items
            ])
            cart.items.all().delete()

            # Trigger the order_created task asynchronously
            order_created.delay(order.id)

            # Set the order in the session
            request.session['order_id'] = order.id

            # Redirect to the payment:process URL
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreationForm()
        cart_items = cart.items.all()  # Populate cart_items with the actual data

    return render(request, 'orders/create.html', {'form': form, 'cart_items': cart_items})


def order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/invoice.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-disposition'] = f'filename=order_{order.order_id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response)
    return response

templates/orders/partials/coupon.html
<div>
    <form hx-post="{% url 'coupons:apply_coupon' %}"
          hx-target="#order-summary"
          hx-swap="innerHTML"
          hx-select="#coupon-section">
        <label for="code" class="mb-2 block text-sm font-medium text-gray-900 dark:text-white"> Enter
            a
            gift card, voucher or promotional code </label>
        <div class="flex max-w-md items-center gap-4">
            <input type="text" id="code" name="code"
                   class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary-500 focus:ring-primary-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder:text-gray-400 dark:focus:border-primary-500 dark:focus:ring-primary-500"
                   placeholder="" required/>
            <button type="submit"
                    class="flex items-center justify-center rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                Apply
            </button>
        </div>
    </form>
</div>

templates/orders/partials/general-information.html
<!-- This <div> represents a form container for collecting general information -->
<div class="p-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2 dark:border-gray-700 sm:p-6 dark:bg-gray-800">
    <!-- Heading for the form section -->
    <h3 class="mb-4 text-xl font-semibold dark:text-white">General information</h3>
    <!-- Horizontal rule for visual separation -->
    <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">
    <!-- Form for capturing user information -->
    <form method="POST" action="{% url 'orders:create_order' %}">
        {% csrf_token %}
        <!-- Grid layout with 6 columns and gap spacing -->
        <div class="grid grid-cols-6 gap-6">
            <!-- First Name input field -->
            <div class="col-span-6 sm:col-span-3">
                <label for="first_name"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">First
                    Name</label>
                <input type="text" name="first_name" id="first_name"
                       class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="Bonnie" required="">
            </div>
            <!-- Last Name input field -->
            <div class="col-span-6 sm:col-span-3">
                <label for="last_name"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Last
                    Name</label>
                <input type="text" name="last_name" id="last_name"
                       class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="Green" required="">
            </div>
            <!-- Email input field -->
            <div class="col-span-6 sm:col-span-3">
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                <input type="email" name="email" id="email"
                       class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="example@company.com" required="">
            </div>
            <!-- Address input field -->
            <div class="col-span-6 sm:col-span-3">
                <label for="address"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Address</label>
                <input type="text" name="address" id="address"
                       class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="e.g. California" required="">
            </div>
            <!-- Country input field -->
            <div class="col-span-6 sm:col-span-3">
                <label for="country"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Country</label>
                <input type="text" name="country" id="country"
                       class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="United States" required="">
            </div>
            <!-- Zip/Postal Code input field -->
            <div class="col-span-6 sm:col-span-3">
                <label for="zip_code"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Zip/postal
                    code</label>
                <input type="number" name="zip_code" id="zip_code"
                       class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                       placeholder="123456" required="">
            </div>
        </div>
        <div class="mt-4 py-2 text-gray-400 dark:border-gray-600">
            <button type="submit"
                    class="w-full flex items-center justify-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-md px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Place Order
            </button>
        </div>
    </form>
</div>

templates/orders/partials/order-item-list.html
{% for item in cart_items %}
<li class="mb-4 p-2 flex py-6" id="order-items-{{ item.product.slug }}">
    <div class="p-4 h-24 w-24 flex-shrink-0 overflow-hidden rounded-md border border-gray-200">
        {% if item.product.images.exists %}
        {% with item.product.images.first as image %}
        <img src="{{ image.image.url }}"
             alt="{{ image.alt_text }}"
             class="h-full w-full object-cover object-center">
        {% endwith %}
        {% endif %}

        <img class="p-8 rounded-t-lg" src="" alt="">


    </div>

    <div class="ml-4 flex flex-1 flex-col">
        <div>
            <div class="flex justify-between text-base font-medium text-gray-900">
                <h3>
                    <a class="font-semibold text-gray-900 dark:text-white"
                       href="{{ item.product.get_absolute_url }}">
                        Apple Macbook Pro 2014</a>
                </h3>

                <div id="item-subtotal">
                    <div class="ml-4 text-gray-900 dark:text-white">

                        <div class="flex">
                            <button hx-delete="{% url 'cart:remove_cart_item' item.product.slug %}"
                                    hx-swap="innerHTML"
                                    hx-target="#order-items"
                                    hx-select="#order-items-{{ item.product.slug }}"
                                    class="font-medium text-red-600 dark:text-red-500 hover:underline">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white"
                                     aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                     width="24" height="24" fill="none" viewBox="0 0 24 24">
                                    <path stroke="currentColor" stroke-linecap="round"
                                          stroke-linejoin="round" stroke-width="2"
                                          d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                                </svg>
                            </button>
                        </div>


                    </div>
                </div>


            </div>
            <p class="mt-1 text-sm text-gray-700 dark:text-gray-400">
                {{ item.product.brand }}</p>
        </div>
        <div class="flex flex-1 items-end justify-between text-sm">

            <div id="">
                                            <span class="font-semibold text-gray-900 dark:text-white"
                                                  id="order-subtotal"
                                                  hx-trigger="update-cart from:body" hx-swap="innerHTML"
                                                  hx-select="#item-subtotal">${{ item.total_price }}</span>
            </div>

            <div class="flex">
                <div class="flex items-center">
                    <button hx-post="{% url 'cart:decrease_item_quantity' item.product.slug %}"
                            hx-swap="outerHTML" hx-target="#quantity-input"
                            hx-select="#quantity-input:value"
                            class="inline-flex items-center justify-center p-1 me-3 text-sm font-medium h-6 w-6 text-gray-500 bg-white border border-gray-300 rounded-lg focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                            type="button">
                        <span class="sr-only">Quantity button</span>
                        <svg class="w-3 h-3" aria-hidden="true"
                             xmlns="http://www.w3.org/2000/svg"
                             fill="none" viewBox="0 0 18 2">
                            <path stroke="currentColor" stroke-linecap="round"
                                  stroke-linejoin="round" stroke-width="2" d="M1 1h16"/>
                        </svg>
                    </button>
                    <div hx-trigger="">
                        <input type="number" id="quantity-input"
                               class="bg-gray-50 w-14 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block px-2.5 py-1 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                               placeholder="{{ item.quantity }}" required/>
                    </div>
                    <button hx-post="{% url 'cart:increase_item_quantity' item.product.slug %}"
                            hx-swap="outerHTML" hx-target="#quantity-input"
                            hx-select="#quantity-input:value"
                            class="inline-flex items-center justify-center h-6 w-6 p-1 ms-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                            type="button">
                        <span class="sr-only">Quantity button</span>
                        <svg class="w-3 h-3" aria-hidden="true"
                             xmlns="http://www.w3.org/2000/svg"
                             fill="none" viewBox="0 0 18 18">
                            <path stroke="currentColor" stroke-linecap="round"
                                  stroke-linejoin="round" stroke-width="2"
                                  d="M9 1v16M1 9h16"/>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </div>
</li>
{% endfor %}

templates/orders/partials/order-summary.html
<div hx-get="{% url 'orders:update_order_summary' %}"
     hx-trigger="update-cart from:body"
     hx-swap="outerHTML" class="mt-6 w-full space-y-6 sm:mt-8 lg:mt-0 lg:max-w-xs xl:max-w-md">
    <div class="flow-root" id="order-summary">
        <div class="-my-3 divide-y divide-gray-200 dark:divide-gray-800">
            <dl id="subtotal-section" class="flex items-center justify-between gap-4 py-3">
                <dt class="text-base font-normal text-gray-500 dark:text-gray-400">Subtotal</dt>
                <dd id="subtotal"
                    hx-get="{% url 'cart:update_cart_summary' %}"
                    hx-trigger="update-cart from:body" hx-swap="innerHTML"
                    hx-select="#subtotal-section" class="text-base font-medium text-gray-900 dark:text-white">
                    ${{ subtotal }}
                </dd>
            </dl>

            {% if cart.coupon %}
            <dl id="coupon-section" class="flex items-center justify-between gap-4 py-3">
                <dt class="text-base font-normal text-gray-500 dark:text-gray-400">Savings</dt>
                <div class="flex items-center">
                    <!-- A form to remove the coupon code -->
                    <form hx-post="{% url 'coupons:remove_coupon' %}">
                        {% csrf_token %}
                        <button type="submit" class="mr-2 lg:mt-2">
                            <svg class="w-5 h-5 text-red-800 dark:text-red-500" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
                                <path stroke="currentColor" stroke-linecap="round"
                                      stroke-linejoin="round"
                                      stroke-width="2"
                                      d="M1 5h16M7 8v8m4-8v8M7 1h4a1 1 0 0 1 1 1v3H6V2a1 1 0 0 1 1-1ZM3 5h12v13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V5Z"/>
                            </svg>
                        </button>
                    </form>
                    <p class="font-medium text-gray-900 truncate dark:text-white">
                        {{ cart.coupon.code }}
                    </p>
                </div>
                <dd id="discount" hx-get=""
                    hx-trigger=""
                    hx-swap="innerHTML" class="text-base font-medium text-green-500">{{ discount }}
                </dd>
            </dl>
            {% endif %}

            <dl id="tax-section" class="flex items-center justify-between gap-4 py-3">
                <dt class="text-base font-normal text-gray-500 dark:text-gray-400">Tax</dt>
                <dd id="tax" hx-get="{% url 'cart:update_cart_summary' %}"
                    hx-trigger="update-cart from:body" hx-swap="innerHTML"
                    hx-select="#tax-section" class="text-base font-medium text-gray-900 dark:text-white">
                    ${{ tax|floatformat:1 }}
                </dd>
            </dl>

            <dl id="total-price-section" class="flex items-center justify-between gap-4 py-3">
                <dt class="text-base font-bold text-gray-900 dark:text-white">Total</dt>
                <dd id="total-price" hx-get="{% url 'cart:update_cart_summary' %}"
                    hx-trigger="update-cart from:body" hx-swap="innerHTML"
                    hx-select="#total-price-section" class="text-base font-bold text-gray-900 dark:text-white">
                    ${{ total_price|floatformat:1 }}
                </dd>
            </dl>
        </div>
    </div>

    <div class="space-y-3">
        <a href="{% url 'payment:process' %}"
           class="flex w-full items-center justify-center rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4  focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
            Proceed to Payment
        </a>

        <p class="text-sm font-normal text-gray-500 dark:text-gray-400">One or more items in your cart
            require an account. <a href="#" title=""
                                   class="font-medium text-primary-700 underline hover:no-underline dark:text-primary-500">Sign
                in or create an account now.</a>.</p>
    </div>
</div>

templates/orders/partials/random.html
<!-- This <div> represents a container for displaying order summary information -->
<div class="p-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
    <!-- Heading for the order summary section -->
    <h3 class="mb-4 text-xl font-semibold dark:text-white">Order summary</h3>

    <!-- Container for tab content related to order details -->
    <div id="fullWidthTabContent" class="border-t border-gray-200 dark:border-gray-600">

        <!-- Section for FAQs related to the order -->
        <div class="pt-4" id="faq" role="tabpanel" aria-labelledby="faq-tab">
            <!-- Unordered list for displaying order items -->
            <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700" id="order-items"
                hx-get="{% url 'orders:get_order_items' %}"
                hx-target="this"
                hx-trigger="update-cart from:body">
                <!-- Including a partial template to render order item list -->
                {% include 'orders/partials/order-item-list.html' %}
            </ul>
        </div>

        <!-- Horizontal rule for visual separation -->
        <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">

        <!-- Including a partial template for handling coupons -->
        {% include 'orders/partials/coupon.html' %}

    </div>

    <!-- Including a partial template for displaying the order summary -->
    {% include 'orders/partials/order-summary.html' %}
</div>