apps/adminpanel/urls.py
from django.urls import path

# from . import views
from . import views

# from .views import views
# from .views import *

app_name = 'adminpanel'

# Root url of "adminpanel" is '', defined in config.urls.py
urlpatterns = [
    path('home/', views.AdminPanelHomeView.as_view(), name='home'),

    # Feedback
    path('feedback/', views.FeedbackListView.as_view(), name='feedback-list'),
    path('feedback/<uuid:uuid>/', views.FeedbackDetailView.as_view(), name='feedback-detail'),
    path('feedback/export/csv/', views.FeedbacksExportToCSV.as_view(), name='export-feedback-to-csv'),
    path('feedback/search/', views.FeedbackSearchView.as_view(), name='feedback-search'),

    # Blog
    path('blog/', views.BlogArticleListView.as_view(), name='blog-article-list'),
    path('blog/<uuid:uuid>/', views.BlogArticleDetailView.as_view(), name='blog-article-detail'),
    path('blog/export/csv/', views.BlogArticleExportToCSV.as_view(), name='blog-article-export-to-csv'),
    path('blog/export/json/', views.BlogArticleExportToJSON.as_view(), name='blog-article-export-to-json'),

    # Component URLs
    path('components/', views.AdminPanelComponentsView.as_view(), name='components'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/', include('apps.accounts.urls')),
    path('', include('apps.products.urls')),
    path('cart/', include('apps.cart.urls')),
    path('order/', include('apps.orders.urls')),
    path('coupon/', include('apps.coupons.urls')),
    path('payment/', include('apps.payment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/adminpanel/views/blog.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count
from django.db.models.functions import TruncDay, TruncWeek, TruncMonth, TruncQuarter, TruncYear
from django.utils import timezone
from django.views.generic import TemplateView, DetailView

from apps.analytics.models import ObjectViewed
from apps.blog.models import Article
from apps.core.utils import ExportToCSVView, ExportToTextView, ExportToJSONView
from .base_views import BaseAdminPanelListView

User = get_user_model()


# Views
# Blog views
class BlogArticleListView(BaseAdminPanelListView):
    model = Article
    template_name = 'adminpanel/blog/list.html'


class BlogArticleDetailView(UserPassesTestMixin, DetailView):
    model = Article
    template_name = 'adminpanel/blog/detail.html'
    context_object_name = 'object'
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        content_type = ContentType.objects.get_for_model(self.model)

        # Fetch related ObjectViewed items
        context['object_views'] = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id)

        unique_views = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).values(
            'user_session__session_key').annotate(count=Count('user_session__session_key')).count()

        # unique_views = (ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id)
        #                 .values('user_session__session_key', 'user_session__expire_date')
        #                 .annotate(count=Count('user_session__session_key'))
        #                 .count())

        context['unique_views'] = unique_views

        # Total views and unique views per day
        views_per_day = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            date=TruncDay('date_viewed')).values('date').annotate(total_views=Count('id'),
                                                                  unique_views=Count('user_session__session_key',
                                                                                     distinct=True))

        # Total views and unique views per week
        views_per_week = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            week=TruncWeek('date_viewed')).values('week').annotate(total_views=Count('id'),
                                                                   unique_views=Count('user_session__session_key',
                                                                                      distinct=True))

        # Total views and unique views per month
        views_per_month = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            month=TruncMonth('date_viewed')).values('month').annotate(total_views=Count('id'),
                                                                      unique_views=Count('user_session__session_key',
                                                                                         distinct=True))

        views_per_quarter = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            month=TruncQuarter('date_viewed')).values('month').annotate(total_views=Count('id'),
                                                                        unique_views=Count('user_session__session_key',
                                                                                           distinct=True))

        views_per_year = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            month=TruncYear('date_viewed')).values('month').annotate(total_views=Count('id'),
                                                                     unique_views=Count('user_session__session_key',
                                                                                        distinct=True))

        context['views_per_day'] = views_per_day
        context['views_per_week'] = views_per_week
        context['views_per_month'] = views_per_month
        context['views_per_quarter'] = views_per_quarter
        context['views_per_year'] = views_per_year

        return context

    def test_func(self):
        return self.request.user.is_staff


class BlogArticleExportToCSV(ExportToCSVView):
    model = Article
    filename = f'article {timezone.now().strftime("(%Y-%m-%d %H-%M-%S)")}.csv'


class BlogArticleExportToJSON(ExportToJSONView):
    model = Article
    filename = f'article {timezone.now().strftime("(%Y-%m-%d %H-%M-%S)")}.json'


# Component views
class AdminPanelComponentsView(TemplateView):
    template_name = 'adminpanel/components.html'

templates/adminpanel/blog/partials/table-container.html
<div id="table-container" class="inline-block min-w-full py-4 align-middle">
    <table class="min-w-full divide-y divide-gray-300">
        <thead class="bg-gray-50 text-xs font-semibold text-gray-700 uppercase">
        <tr>
            <th scope="col"
                class="whitespace-nowrap px-4 py-3.5 text-left">
                ID
            </th>
            <th scope="col"
                class="whitespace-nowrap px-2 py-3.5 text-left">
                Name
            </th>
            <th scope="col"
                class="whitespace-nowrap px-2 py-3.5 text-left">
                Release status
            </th>
            <th scope="col"
                class="whitespace-nowrap px-2 py-3.5 text-left">
                Date released
            </th>
            <th scope="col" class="relative whitespace-nowrap px-4 py-3.5">
                <span class="sr-only">Edit</span>
            </th>
        </tr>
        </thead>


        <tbody id="table-tbody" class="divide-y divide-gray-200 bg-white">
        {% for object in objects %}
            <tr class="group">
                <td class="whitespace-nowrap px-4 py-2 text-sm text-muted group-hover:bg-indigo-50">{{ object.id }}</td>
                <td class="whitespace-nowrap px-2 py-2 text-sm text-muted group-hover:bg-indigo-50"><a
                        href="{{ object.title }}"
                        class="hover:text-indigo-600 hover:underline">{{ object.title }}</a>
                </td>
                <td class="whitespace-nowrap px-2 py-2 text-sm text-muted group-hover:bg-indigo-50">{{ object.release_status }}</td>
                {% if object.date_released %}
                    <td class="whitespace-nowrap px-2 py-2 text-sm text-muted group-hover:bg-indigo-50 convert-time"
                        data-utc-time="{{ object.date_released.isoformat }}"></td>
                {% else %}
                    <td class="whitespace-nowrap px-2 py-2 text-sm text-muted group-hover:bg-indigo-50">-</td>
                {% endif %}
                <td class="relative whitespace-nowrap px-4 py-2 text-right text-sm font-medium group-hover:bg-indigo-50">
                    <a href="{% url 'adminpanel:blog-article-detail' uuid=object.uuid %}"
                       class="text-indigo-600 hover:text-indigo-900">Edit</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>


    </table>

    <div class="border-t border-gray-200">
        <div class="flex items-center justify-between border-t border-gray-200 bg-white py-3">
            <div class="flex flex-1 justify-between sm:hidden">
                <a href="#"
                   class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">Previous</a>
                <a href="#"
                   class="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">Next</a>
            </div>
            <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
                <div>
                    <p class="text-sm text-gray-700">
                        Showing
                        <span class="font-medium">{{ start_page }}</span>
                        to
                        <span class="font-medium">{{ end_page }}</span>
                        of
                        <span class="font-medium">{{ paginator.count }}</span>
                        results
                    </p>

                </div>
                <div>


                    <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm"
                         aria-label="Pagination">

                        {% if objects.has_previous %}
                            <a href="?page={{ objects.previous_page_number }}"
                               class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                                <span class="sr-only">Previous</span>
                                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"
                                     aria-hidden="true">
                                    <path fill-rule="evenodd"
                                          d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z"
                                          clip-rule="evenodd"/>
                                </svg>
                            </a>
                        {% else %}
                            <a href="#"
                               class="opacity-40 relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                                <span class="sr-only">Previous</span>
                                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"
                                     aria-hidden="true">
                                    <path fill-rule="evenodd"
                                          d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z"
                                          clip-rule="evenodd"/>
                                </svg>
                            </a>
                        {% endif %}

                        <!-- Current: "z-10 bg-indigo-600 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", Default: "text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:outline-offset-0" -->
                        {#                                                <a href="?page=1"#}
                        {#                                                   class="{% if feedbacks.number == 1 %}bg-indigo-600 text-white{% else %}text-gray-900{% endif %} relative inline-flex items-center px-4 py-2 text-sm font-semibold ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">1</a>#}

                        {#                                                {% if feedbacks.number == 1 %}#}
                        {#                                                    <a href="?page=1" aria-current="page"#}
                        {#                                                       class="relative z-10 inline-flex items-center bg-indigo-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">1</a>#}
                        {#                                                {% else %}#}
                        {#                                                    <a href="?page=1" aria-current="page"#}
                        {#                                                       class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">1</a>#}
                        {#                                                {% endif %}#}


                        {% if objects.number > 2 %}
                            <a href="?page=1"
                               class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">1</a>
                            <span class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-700 ring-1 ring-inset ring-gray-300 focus:outline-offset-0">...</span>
                        {% endif %}

                        <!-- 3 pages before the current page -->
                        {% for page_num in page_range %}
                            {% if page_num == objects.number %}
                                <!-- Current Page -->
                                <a href="#" aria-current="page"
                                   class="relative z-10 inline-flex items-center bg-indigo-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">{{ page_num }}</a>
                            {% else %}
                                <!-- Other Pages -->
                                <a href="?page={{ page_num }}"
                                   class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">{{ page_num }}</a>
                            {% endif %}
                        {% endfor %}



                        {#                                                <a href="#"#}
                        {#                                                   class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">2</a>#}
                        {#                                                <a href="#"#}
                        {#                                                   class="relative hidden items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 md:inline-flex">3</a>#}

                        {% if objects.number < objects.paginator.num_pages|add:-1 %}
                            <span class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-700 ring-1 ring-inset ring-gray-300 focus:outline-offset-0">...</span>
                        {% endif %}

                        {#                                                <a href="#"#}
                        {#                                                   class="relative hidden items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 md:inline-flex">8</a>#}
                        {#                                                <a href="#"#}
                        {#                                                   class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">9</a>#}
                        {#                                                <a href="#"#}
                        {#                                                   class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">10</a>#}

                        {% if objects.has_next %}

                            <a href="?{% if table_search %}table_search={{ table_search }}&{% endif %}page={{ objects.next_page_number }}"
                               class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                                <span class="sr-only">Next</span>
                                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"
                                     aria-hidden="true">
                                    <path fill-rule="evenodd"
                                          d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
                                          clip-rule="evenodd"/>
                                </svg>
                            </a>
                        {% else %}
                            <button
                                    class="opacity-40 relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                                <span class="sr-only">Next</span>
                                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"
                                     aria-hidden="true">
                                    <path fill-rule="evenodd"
                                          d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
                                          clip-rule="evenodd"/>
                                </svg>
                            </button>
                        {% endif %}

                    </nav>

                    <div>
                        table_search: {{ table_search }}
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>