apps/adminpanel/urls.py
from django.urls import path

# from . import views
from . import views

# from .views import views
# from .views import *

app_name = 'adminpanel'

# Root url of "adminpanel" is '', defined in config.urls.py
urlpatterns = [
    path('home/', views.AdminPanelHomeView.as_view(), name='home'),

    # Feedback
    path('feedback/', views.FeedbackListView.as_view(), name='feedback-list'),
    path('feedback/<uuid:uuid>/', views.FeedbackDetailView.as_view(), name='feedback-detail'),
    path('feedback/export/csv/', views.FeedbacksExportToCSV.as_view(), name='export-feedback-to-csv'),
    path('feedback/search/', views.FeedbackSearchView.as_view(), name='feedback-search'),

    # Blog
    path('blog/', views.BlogArticleListView.as_view(), name='blog-article-list'),
    path('blog/<uuid:uuid>/', views.BlogArticleDetailView.as_view(), name='blog-article-detail'),
    path('blog/export/csv/', views.BlogArticleExportToCSV.as_view(), name='blog-article-export-to-csv'),
    path('blog/export/json/', views.BlogArticleExportToJSON.as_view(), name='blog-article-export-to-json'),

    # Component URLs
    path('components/', views.AdminPanelComponentsView.as_view(), name='components'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/', include('apps.accounts.urls')),
    path('', include('apps.products.urls')),
    path('cart/', include('apps.cart.urls')),
    path('order/', include('apps.orders.urls')),
    path('coupon/', include('apps.coupons.urls')),
    path('payment/', include('apps.payment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/adminpanel/views/base_views.py
import logging

from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from django.db.models import Q


# Base views
class BaseAdminPanelTemplateView(UserPassesTestMixin, TemplateView):
    def test_func(self):
        return self.request.user.is_staff


class BaseAdminPanelListView(UserPassesTestMixin, ListView):
    paginate_by = 2
    PAGINATION_PAGES_BEFORE_AND_AFTER = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        logging.debug('LIST VIEW CALLED')

        page_obj = context['page_obj']
        paginator = context['paginator']
        current_page = page_obj.number
        total_pages = paginator.num_pages

        start_page_num = (current_page - 1) * self.paginate_by + 1
        end_page_num = start_page_num + len(page_obj.object_list) - 1

        context['start_page'] = start_page_num
        context['end_page'] = end_page_num
        context['objects'] = page_obj
        context['page_range'] = range(
            max(1, current_page - self.PAGINATION_PAGES_BEFORE_AND_AFTER),
            min(total_pages, current_page + self.PAGINATION_PAGES_BEFORE_AND_AFTER) + 1
        )

        return context

    def test_func(self):
        return self.request.user.is_staff


class BaseAdminPanelSearchView(UserPassesTestMixin, TemplateView):
    model = None  # Should be overridden by subclass
    search_fields = None  # Default search fields, can be overridden
    search_key = 'list_search'

    def get_search_text(self):
        return self.request.GET.get(self.search_key, None)

    def get_queryset(self):
        search_text = self.get_search_text()

        if search_text:
            # Construct the Q objects for each search field
            query = Q()

            for field in self.search_fields:
                query |= Q(**{f'{field}__icontains': search_text})
            return self.model.objects.filter(query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_items'] = self.get_queryset()
        print(context)
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def test_func(self):
        return self.request.user.is_staff


class BaseAdminPanelSearchListView(UserPassesTestMixin, ListView):
    model = None  # Should be overridden by subclass
    search_fields = []  # Default search fields, can be overridden. Should be a list
    search_key = 'list_search'
    paginate_by = 2
    PAGINATION_PAGES_BEFORE_AND_AFTER = 1

    def get_search_text(self):
        return self.request.GET.get(self.search_key, None)

    def get_queryset(self):
        search_text = self.get_search_text()
        logging.debug(f'search_text = {search_text}')

        if search_text:
            # Construct the Q objects for each search field
            query = Q()

            for field in self.search_fields:
                query |= Q(**{f'{field}__icontains': search_text})
            return self.model.objects.filter(query)
        else:
            return super().get_queryset()  # Call the parent class's get_queryset if no search_text

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page_obj = context['page_obj']
        paginator = context['paginator']
        current_page = page_obj.number
        total_pages = paginator.num_pages

        start_page_num = (current_page - 1) * self.paginate_by + 1
        end_page_num = start_page_num + len(page_obj.object_list) - 1

        context['start_page'] = start_page_num
        context['end_page'] = end_page_num
        context['list_items'] = page_obj
        context['page_range'] = range(
            max(1, current_page - self.PAGINATION_PAGES_BEFORE_AND_AFTER),
            min(total_pages, current_page + self.PAGINATION_PAGES_BEFORE_AND_AFTER) + 1
        )
        context[self.search_key] = self.get_search_text()  # Add the current search text to the context
        context['table_search'] = self.get_search_text()

        return context

    def test_func(self):
        return self.request.user.is_staff

apps/adminpanel/views/blog.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count
from django.db.models.functions import TruncDay, TruncWeek, TruncMonth, TruncQuarter, TruncYear
from django.utils import timezone
from django.views.generic import TemplateView, DetailView

from apps.analytics.models import ObjectViewed
from apps.blog.models import Article
from apps.core.utils import ExportToCSVView, ExportToTextView, ExportToJSONView
from .base_views import BaseAdminPanelListView

User = get_user_model()


# Views
# Blog views
class BlogArticleListView(BaseAdminPanelListView):
    model = Article
    template_name = 'adminpanel/blog/list.html'


class BlogArticleDetailView(UserPassesTestMixin, DetailView):
    model = Article
    template_name = 'adminpanel/blog/detail.html'
    context_object_name = 'object'
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        content_type = ContentType.objects.get_for_model(self.model)

        # Fetch related ObjectViewed items
        context['object_views'] = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id)

        unique_views = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).values(
            'user_session__session_key').annotate(count=Count('user_session__session_key')).count()

        # unique_views = (ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id)
        #                 .values('user_session__session_key', 'user_session__expire_date')
        #                 .annotate(count=Count('user_session__session_key'))
        #                 .count())

        context['unique_views'] = unique_views

        # Total views and unique views per day
        views_per_day = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            date=TruncDay('date_viewed')).values('date').annotate(total_views=Count('id'),
                                                                  unique_views=Count('user_session__session_key',
                                                                                     distinct=True))

        # Total views and unique views per week
        views_per_week = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            week=TruncWeek('date_viewed')).values('week').annotate(total_views=Count('id'),
                                                                   unique_views=Count('user_session__session_key',
                                                                                      distinct=True))

        # Total views and unique views per month
        views_per_month = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            month=TruncMonth('date_viewed')).values('month').annotate(total_views=Count('id'),
                                                                      unique_views=Count('user_session__session_key',
                                                                                         distinct=True))

        views_per_quarter = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            month=TruncQuarter('date_viewed')).values('month').annotate(total_views=Count('id'),
                                                                        unique_views=Count('user_session__session_key',
                                                                                           distinct=True))

        views_per_year = ObjectViewed.objects.filter(content_type=content_type, object_id=self.object.id).annotate(
            month=TruncYear('date_viewed')).values('month').annotate(total_views=Count('id'),
                                                                     unique_views=Count('user_session__session_key',
                                                                                        distinct=True))

        context['views_per_day'] = views_per_day
        context['views_per_week'] = views_per_week
        context['views_per_month'] = views_per_month
        context['views_per_quarter'] = views_per_quarter
        context['views_per_year'] = views_per_year

        return context

    def test_func(self):
        return self.request.user.is_staff


class BlogArticleExportToCSV(ExportToCSVView):
    model = Article
    filename = f'article {timezone.now().strftime("(%Y-%m-%d %H-%M-%S)")}.csv'


class BlogArticleExportToJSON(ExportToJSONView):
    model = Article
    filename = f'article {timezone.now().strftime("(%Y-%m-%d %H-%M-%S)")}.json'


# Component views
class AdminPanelComponentsView(TemplateView):
    template_name = 'adminpanel/components.html'

apps/adminpanel/views/feedback.py
import logging

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView, DetailView
from django.utils import timezone

from apps.feedback.models import Feedback
from .base_views import BaseAdminPanelTemplateView, BaseAdminPanelListView, BaseAdminPanelSearchListView

from apps.core.utils import ExportToCSVView, ExportToTextView, ExportToJSONView

User = get_user_model()


# Feedback view
class FeedbackListView(BaseAdminPanelSearchListView):
    model = Feedback
    template_name = 'adminpanel/feedback/list.html'
    search_fields = ['content']
    search_key = 'table_search'


class FeedbackSearchView(BaseAdminPanelSearchListView):
    model = Feedback
    template_name = 'adminpanel/feedback/partials/table-container.html'
    search_fields = ['content']
    search_key = 'table_search'


class FeedbacksExportToCSV(ExportToCSVView):
    model = Feedback
    filename = f'feedbacks {timezone.now().strftime("(%Y-%m-%d %H-%M-%S)")}.csv'


class FeedbackDetailView(UserPassesTestMixin, DetailView):
    model = Feedback
    template_name = 'adminpanel/feedback/detail.html'
    context_object_name = 'feedback'
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    def test_func(self):
        return self.request.user.is_staff

apps/adminpanel/views/general.py
import logging

from django.contrib.auth import get_user_model
from django.views.generic import TemplateView

from apps.feedback.models import Feedback
from .base_views import BaseAdminPanelTemplateView

User = get_user_model()


class AdminPanelHomeView(BaseAdminPanelTemplateView):
    template_name = 'adminpanel/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Admin Panel'

        # Get all users and date_created property
        users = User.objects.all().values('username', 'email', 'date_joined', 'is_staff', 'is_admin', 'is_superuser')
        feedback_count = Feedback.objects.filter(is_processed=False).count()
        feedback = Feedback.objects.all()

        # feedback_last_week_percent_change = Feedback.percent_change_last_week()
        feedback_last_week_percent_change = 'HARDCODED'

        logging.debug(f'feedback_last_week_percent_change: {feedback_last_week_percent_change}')

        context['users'] = users
        context['feedback_count'] = feedback_count
        context['feedback_last_week_percent_change'] = feedback_last_week_percent_change
        context['feedback'] = feedback
        return context


# Component views
class AdminPanelComponentsView(TemplateView):
    template_name = 'adminpanel/components.html'

templates/adminpanel/components/read-only-properties.html
<div class="text-gray-800 bg-gray-50 p-2 border border-gray-200 rounded">
    <h3 class="text-gray-800 font-medium text-lg border-b pb-2">Read only properties</h3>
    <div class="space-y-2 divide-y divide-transparent mt-2 text-xs">

        {% if object.id %}
            <dl class="grid grid-cols-1 sm:grid-cols-3">
                <dt class="font-medium text-muted">ID</dt>
                <dd class="sm:col-span-2 text-normal">{{ object.id }}</dd>
            </dl>
        {% endif %}

        {% if object.uuid %}
            <dl class="grid grid-cols-1 sm:grid-cols-3">
                <dt class="font-medium text-muted">UUID</dt>
                <dd class="sm:col-span-2 text-normal">{{ object.uuid }}</dd>
            </dl>
        {% endif %}

        {% if object.date_created %}
            <dl class="grid grid-cols-1 sm:grid-cols-3">
                <dt class="font-medium text-muted">Date created</dt>
                <dd class="sm:col-span-2 text-normal">
                    <div class="flex">
                        <div class="w-12 text-muted">
                            Server
                        </div>
                        <div>
                            {{ object.date_created|date:"m/d/Y, h:i:s A" }}
                        </div>
                    </div>
                    <div class="flex">
                        <div class="w-12 text-muted">
                            Local
                        </div>
                        <div data-utc-time="{{ object.date_created.isoformat }}"
                             class="convert-time">
                            {{ object.date_created|date:"m/d/Y, h:i:s A" }}
                        </div>
                    </div>
                </dd>
            </dl>
        {% endif %}

        {% if object.date_modified %}
            <dl class="grid grid-cols-1 sm:grid-cols-3">
                <dt class="font-medium text-muted">Date modified</dt>
                <dd class="sm:col-span-2 text-normal">
                    <div class="flex">
                        <div class="w-12 text-muted">
                            Server
                        </div>
                        <div>
                            {{ object.date_modified|date:"m/d/Y, h:i:s A" }}
                        </div>
                    </div>
                    <div class="flex">
                        <div class="w-12 text-muted">
                            Local
                        </div>
                        <div data-utc-time="{{ object.date_modified.isoformat }}"
                             class="convert-time">
                            {{ object.date_modified|date:"m/d/Y, h:i:s A" }}
                        </div>
                    </div>
                </dd>
            </dl>
        {% endif %}

    </div>
</div>

templates/adminpanel/components/sidebar.html
<aside class="overflow-x-auto border-b border-gray-900/5 py-4 lg:block lg:w-64 lg:flex-none lg:border-0">
    <nav class="flex-none px-4 sm:px-6 lg:px-0">
        <ul role="list" class="gap-x-3 gap-y-1 whitespace-nowrap lg:flex-col">

            <li>
                {% if request.resolver_match.url_name == 'home' %}
                    <a href="{% url 'adminpanel:home' %}"
                       class="bg-gray-100 text-indigo-600 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        General
                    </a>
                {% else %}
                    <a href="{% url 'adminpanel:home' %}"
                       class="text-gray-700 hover:text-gray-800 hover:bg-gray-50 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        General
                    </a>
                {% endif %}
            </li>

            <li>
                {% if request.resolver_match.url_name == 'tbd' %}
                    <a href="#"
                       class="bg-gray-100 text-indigo-600 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        Analytics
                    </a>
                {% else %}
                    <a href="#"
                       class="text-gray-700 hover:text-gray-800 hover:bg-gray-50 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        Analytics
                    </a>
                {% endif %}
            </li>

            <li>
                {% if request.resolver_match.url_name == 'feedback-list' %}
                    <a href="{% url 'adminpanel:feedback-list' %}"
                       class="bg-gray-100 text-indigo-600 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        Feedback
                    </a>
                {% else %}
                    <a href="{% url 'adminpanel:feedback-list' %}"
                       class="text-gray-700 hover:text-gray-800 hover:bg-gray-50 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        Feedback
                    </a>
                {% endif %}
            </li>


            <li>
                {% if request.resolver_match.url_name == 'blog-article-list' %}
                    <a href="{% url 'adminpanel:blog-article-list' %}"
                       class="bg-gray-100 text-indigo-600 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        Blog
                    </a>
                {% else %}
                    <a href="{% url 'adminpanel:blog-article-list' %}"
                       class="text-gray-700 hover:text-gray-800 hover:bg-gray-50 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        Blog
                    </a>
                {% endif %}
            </li>



            {% if user.is_staff %}
                <hr class="mt-4 pb-4">
                <li>
                    {% if request.resolver_match.url_name == 'components' %}
                        <a href="{% url 'adminpanel:components' %}"
                           class="bg-gray-100 text-indigo-600 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                            <svg class="h-6 w-6 shrink-0 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none"
                                 viewBox="0 0 24 24" stroke-width="1.5"
                                 stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M14.25 6.087c0-.355.186-.676.401-.959.221-.29.349-.634.349-1.003 0-1.036-1.007-1.875-2.25-1.875s-2.25.84-2.25 1.875c0 .369.128.713.349 1.003.215.283.401.604.401.959v0a.64.64 0 01-.657.643 48.39 48.39 0 01-4.163-.3c.186 1.613.293 3.25.315 4.907a.656.656 0 01-.658.663v0c-.355 0-.676-.186-.959-.401a1.647 1.647 0 00-1.003-.349c-1.036 0-1.875 1.007-1.875 2.25s.84 2.25 1.875 2.25c.369 0 .713-.128 1.003-.349.283-.215.604-.401.959-.401v0c.31 0 .555.26.532.57a48.039 48.039 0 01-.642 5.056c1.518.19 3.058.309 4.616.354a.64.64 0 00.657-.643v0c0-.355-.186-.676-.401-.959a1.647 1.647 0 01-.349-1.003c0-1.035 1.008-1.875 2.25-1.875 1.243 0 2.25.84 2.25 1.875 0 .369-.128.713-.349 1.003-.215.283-.4.604-.4.959v0c0 .333.277.599.61.58a48.1 48.1 0 005.427-.63 48.05 48.05 0 00.582-4.717.532.532 0 00-.533-.57v0c-.355 0-.676.186-.959.401-.29.221-.634.349-1.003.349-1.035 0-1.875-1.007-1.875-2.25s.84-2.25 1.875-2.25c.37 0 .713.128 1.003.349.283.215.604.401.96.401v0a.656.656 0 00.658-.663 48.422 48.422 0 00-.37-5.36c-1.886.342-3.81.574-5.766.689a.578.578 0 01-.61-.58v0z"/>
                            </svg>
                            Components
                        </a>
                    {% else %}
                        <a href="{% url 'adminpanel:components' %}"
                           class="text-gray-700 hover:text-gray-800 hover:bg-gray-50 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                            <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-gray-500"
                                 xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                 stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M14.25 6.087c0-.355.186-.676.401-.959.221-.29.349-.634.349-1.003 0-1.036-1.007-1.875-2.25-1.875s-2.25.84-2.25 1.875c0 .369.128.713.349 1.003.215.283.401.604.401.959v0a.64.64 0 01-.657.643 48.39 48.39 0 01-4.163-.3c.186 1.613.293 3.25.315 4.907a.656.656 0 01-.658.663v0c-.355 0-.676-.186-.959-.401a1.647 1.647 0 00-1.003-.349c-1.036 0-1.875 1.007-1.875 2.25s.84 2.25 1.875 2.25c.369 0 .713-.128 1.003-.349.283-.215.604-.401.959-.401v0c.31 0 .555.26.532.57a48.039 48.039 0 01-.642 5.056c1.518.19 3.058.309 4.616.354a.64.64 0 00.657-.643v0c0-.355-.186-.676-.401-.959a1.647 1.647 0 01-.349-1.003c0-1.035 1.008-1.875 2.25-1.875 1.243 0 2.25.84 2.25 1.875 0 .369-.128.713-.349 1.003-.215.283-.4.604-.4.959v0c0 .333.277.599.61.58a48.1 48.1 0 005.427-.63 48.05 48.05 0 00.582-4.717.532.532 0 00-.533-.57v0c-.355 0-.676.186-.959.401-.29.221-.634.349-1.003.349-1.035 0-1.875-1.007-1.875-2.25s.84-2.25 1.875-2.25c.37 0 .713.128 1.003.349.283.215.604.401.96.401v0a.656.656 0 00.658-.663 48.422 48.422 0 00-.37-5.36c-1.886.342-3.81.574-5.766.689a.578.578 0 01-.61-.58v0z"/>
                            </svg>
                            Components
                        </a>
                    {% endif %}
                </li>
                <li>
                    <a href="{% url 'adminpanel:home' %}"
                       class="text-gray-700 hover:text-gray-800 hover:bg-gray-50 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-gray-500"
                             xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                             stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z"/>
                        </svg>
                        Admin panel
                    </a>
                </li>
            {% endif %}
            {% if user.is_superuser %}
                <li>
                    <a href="{% url 'admin:index' %}"
                       class="text-gray-700 hover:text-gray-800 hover:bg-gray-50 group flex gap-x-3 rounded-md py-2 pl-2 pr-3 text-sm leading-6 font-semibold">
                        <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-gray-500"
                             xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                             stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M12 8.25v-1.5m0 1.5c-1.355 0-2.697.056-4.024.166C6.845 8.51 6 9.473 6 10.608v2.513m6-4.87c1.355 0 2.697.055 4.024.165C17.155 8.51 18 9.473 18 10.608v2.513m-3-4.87v-1.5m-6 1.5v-1.5m12 9.75l-1.5.75a3.354 3.354 0 01-3 0 3.354 3.354 0 00-3 0 3.354 3.354 0 01-3 0 3.354 3.354 0 00-3 0 3.354 3.354 0 01-3 0L3 16.5m15-3.38a48.474 48.474 0 00-6-.37c-2.032 0-4.034.125-6 .37m12 0c.39.049.777.102 1.163.16 1.07.16 1.837 1.094 1.837 2.175v5.17c0 .62-.504 1.124-1.125 1.124H4.125A1.125 1.125 0 013 20.625v-5.17c0-1.08.768-2.014 1.837-2.174A47.78 47.78 0 016 13.12M12.265 3.11a.375.375 0 11-.53 0L12 2.845l.265.265zm-3 0a.375.375 0 11-.53 0L9 2.845l.265.265zm6 0a.375.375 0 11-.53 0L15 2.845l.265.265z"/>
                        </svg>
                        Django panel
                    </a>
                </li>
            {% endif %}

        </ul>
    </nav>
</aside>